<?php

return [
    "template_key" => "departments",
    "template_name" => "Departamentos",
    "simple_fields" => [
        ["field_key" => "hero_title", "label" => "Titulo principal", "field_type" => "text", "default" => "Departamentos", "default_visible" => 1],
        ["field_key" => "hero_subtitle", "label" => "Subtitulo principal", "field_type" => "textarea", "default" => "Conoce nuestras areas de atencion especializadas, disenadas para acompanar cada etapa del cuidado de tu salud.", "default_visible" => 1],
        ["field_key" => "intro_title", "label" => "Titulo introductorio", "field_type" => "text", "default" => "Atencion integral por especialidad", "default_visible" => 1],
        ["field_key" => "intro_text", "label" => "Texto introductorio", "field_type" => "textarea", "default" => "Reunimos profesionales, tecnologia y procesos coordinados para brindar una experiencia clara, cercana y segura en cada servicio.", "default_visible" => 1],
        ["field_key" => "section_title", "label" => "Titulo de seccion", "field_type" => "text", "default" => "Nuestros departamentos", "default_visible" => 1],
        ["field_key" => "section_subtitle", "label" => "Subtitulo de seccion", "field_type" => "textarea", "default" => "Explora las principales areas de atencion disponibles para pacientes y familias.", "default_visible" => 1],
        ["field_key" => "cta_title", "label" => "Titulo CTA", "field_type" => "text", "default" => "Necesitas orientacion para elegir un servicio?", "default_visible" => 1],
        ["field_key" => "cta_text", "label" => "Texto CTA", "field_type" => "textarea", "default" => "Nuestro equipo puede ayudarte a identificar el departamento adecuado segun tus necesidades de atencion.", "default_visible" => 1],
        ["field_key" => "cta_button_text", "label" => "Texto boton CTA", "field_type" => "text", "default" => "Solicitar informacion", "default_visible" => 1],
        ["field_key" => "cta_button_link_type", "label" => "Tipo de enlace boton CTA", "field_type" => "text", "default" => "custom", "default_visible" => 1],
        ["field_key" => "cta_button_page_id", "label" => "Pagina interna boton CTA", "field_type" => "text", "default" => "", "default_visible" => 1],
        ["field_key" => "cta_button_url", "label" => "URL boton CTA", "field_type" => "url", "default" => "contact.html", "default_visible" => 1],
    ],
    "repeaters" => [
        [
            "repeater_key" => "departments",
            "label" => "Departamentos",
            "fields" => [
                ["field_key" => "icon_class", "label" => "Icono", "field_type" => "text", "default" => ""],
                ["field_key" => "title", "label" => "Titulo", "field_type" => "text", "default" => ""],
                ["field_key" => "subtitle", "label" => "Subtitulo", "field_type" => "text", "default" => ""],
                ["field_key" => "description", "label" => "Descripcion", "field_type" => "textarea", "default" => ""],
                ["field_key" => "image", "label" => "Imagen", "field_type" => "image", "default" => ""],
                ["field_key" => "image_alt", "label" => "Texto alternativo imagen", "field_type" => "text", "default" => ""],
                ["field_key" => "stats_number", "label" => "Numero destacado", "field_type" => "text", "default" => ""],
                ["field_key" => "stats_label", "label" => "Etiqueta del numero", "field_type" => "text", "default" => ""],
                ["field_key" => "feature_1", "label" => "Caracteristica 1", "field_type" => "text", "default" => ""],
                ["field_key" => "feature_2", "label" => "Caracteristica 2", "field_type" => "text", "default" => ""],
                ["field_key" => "feature_3", "label" => "Caracteristica 3", "field_type" => "text", "default" => ""],
                ["field_key" => "layout_variant", "label" => "Variante de layout", "field_type" => "text", "default" => "card"],
                ["field_key" => "featured_badge_text", "label" => "Texto badge destacado", "field_type" => "text", "default" => ""],
                ["field_key" => "achievement_1_icon", "label" => "Icono logro 1", "field_type" => "text", "default" => ""],
                ["field_key" => "achievement_1_text", "label" => "Texto logro 1", "field_type" => "text", "default" => ""],
                ["field_key" => "achievement_2_icon", "label" => "Icono logro 2", "field_type" => "text", "default" => ""],
                ["field_key" => "achievement_2_text", "label" => "Texto logro 2", "field_type" => "text", "default" => ""],
                ["field_key" => "tag_1", "label" => "Etiqueta 1", "field_type" => "text", "default" => ""],
                ["field_key" => "tag_2", "label" => "Etiqueta 2", "field_type" => "text", "default" => ""],
                ["field_key" => "tag_3", "label" => "Etiqueta 3", "field_type" => "text", "default" => ""],
                ["field_key" => "tag_4", "label" => "Etiqueta 4", "field_type" => "text", "default" => ""],
                ["field_key" => "button_text", "label" => "Texto del boton", "field_type" => "text", "default" => ""],
                ["field_key" => "button_link_type", "label" => "Tipo de enlace", "field_type" => "text", "default" => "custom"],
                ["field_key" => "button_page_id", "label" => "Pagina interna", "field_type" => "text", "default" => ""],
                ["field_key" => "button_url", "label" => "URL del boton", "field_type" => "url", "default" => ""],
            ],
            "items" => [
                ["item_index" => 0, "item_label" => "Cardiologia", "default_visible" => 1, "defaults" => ["icon_class" => "bi bi-heart-pulse", "title" => "Cardiologia", "subtitle" => "Cuidado cardiovascular", "description" => "Evaluacion, diagnostico y seguimiento de condiciones del corazon y el sistema vascular.", "image" => "assets/img/health/cardiology-2.webp", "image_alt" => "Cardiologia", "stats_number" => "500+", "stats_label" => "Procedimientos", "feature_1" => "Cirugia cardiaca avanzada", "feature_2" => "Cardiologia intervencionista", "feature_3" => "Manejo del ritmo cardiaco", "layout_variant" => "card", "featured_badge_text" => "", "achievement_1_icon" => "", "achievement_1_text" => "", "achievement_2_icon" => "", "achievement_2_text" => "", "tag_1" => "", "tag_2" => "", "tag_3" => "", "tag_4" => "", "button_text" => "Ver mas", "button_link_type" => "custom", "button_page_id" => "", "button_url" => "department-details.html"]],
                ["item_index" => 1, "item_label" => "Dermatologia", "default_visible" => 1, "defaults" => ["icon_class" => "bi bi-shield-plus", "title" => "Dermatologia", "subtitle" => "Expertos en piel", "description" => "Atencion especializada para el cuidado de la piel, prevencion y tratamiento dermatologico.", "image" => "assets/img/health/dermatology-3.webp", "image_alt" => "Dermatologia", "stats_number" => "1200+", "stats_label" => "Tratamientos", "feature_1" => "Dermatologia estetica", "feature_2" => "Tratamiento de cancer de piel", "feature_3" => "Terapia laser", "layout_variant" => "card", "featured_badge_text" => "", "achievement_1_icon" => "", "achievement_1_text" => "", "achievement_2_icon" => "", "achievement_2_text" => "", "tag_1" => "", "tag_2" => "", "tag_3" => "", "tag_4" => "", "button_text" => "Ver mas", "button_link_type" => "custom", "button_page_id" => "", "button_url" => "department-details.html"]],
                ["item_index" => 2, "item_label" => "Neurologia", "default_visible" => 1, "defaults" => ["icon_class" => "bi bi-lightning-fill", "title" => "Neurologia", "subtitle" => "Cerebro y sistema nervioso", "description" => "Acompanamiento medico para condiciones del cerebro, nervios y sistema neurologico.", "image" => "assets/img/health/neurology-4.webp", "image_alt" => "Neurologia", "stats_number" => "", "stats_label" => "", "feature_1" => "", "feature_2" => "", "feature_3" => "", "layout_variant" => "featured", "featured_badge_text" => "Destacado", "achievement_1_icon" => "bi bi-award", "achievement_1_text" => "Equipo especializado", "achievement_2_icon" => "bi bi-clock", "achievement_2_text" => "Atencion prioritaria", "tag_1" => "Imagen cerebral", "tag_2" => "Cuidado de epilepsia", "tag_3" => "Tratamiento de ACV", "tag_4" => "Memoria y cognicion", "button_text" => "Explorar departamento", "button_link_type" => "custom", "button_page_id" => "", "button_url" => "department-details.html"]],
                ["item_index" => 3, "item_label" => "Ortopedia", "default_visible" => 1, "defaults" => ["icon_class" => "bi bi-bandaid", "title" => "Ortopedia", "subtitle" => "Huesos y articulaciones", "description" => "Servicios orientados al cuidado de huesos, articulaciones, lesiones y movilidad.", "image" => "assets/img/health/orthopedics-4.webp", "image_alt" => "Ortopedia", "stats_number" => "800+", "stats_label" => "Cirugias", "feature_1" => "Reemplazo articular", "feature_2" => "Medicina deportiva", "feature_3" => "Cirugia de columna", "layout_variant" => "card", "featured_badge_text" => "", "achievement_1_icon" => "", "achievement_1_text" => "", "achievement_2_icon" => "", "achievement_2_text" => "", "tag_1" => "", "tag_2" => "", "tag_3" => "", "tag_4" => "", "button_text" => "Ver mas", "button_link_type" => "custom", "button_page_id" => "", "button_url" => "department-details.html"]],
                ["item_index" => 4, "item_label" => "Pediatria", "default_visible" => 1, "defaults" => ["icon_class" => "bi bi-emoji-smile", "title" => "Pediatria", "subtitle" => "Salud infantil", "description" => "Cuidado integral para ninos y adolescentes, con enfoque preventivo y familiar.", "image" => "assets/img/health/pediatrics-2.webp", "image_alt" => "Pediatria", "stats_number" => "2000+", "stats_label" => "Pacientes jovenes", "feature_1" => "Cuidado del recien nacido", "feature_2" => "Desarrollo infantil", "feature_3" => "Programas de vacunacion", "layout_variant" => "card", "featured_badge_text" => "", "achievement_1_icon" => "", "achievement_1_text" => "", "achievement_2_icon" => "", "achievement_2_text" => "", "tag_1" => "", "tag_2" => "", "tag_3" => "", "tag_4" => "", "button_text" => "Ver mas", "button_link_type" => "custom", "button_page_id" => "", "button_url" => "department-details.html"]],
            ],
        ],
    ],
];
