<?php

return [
    "template_key" => "home",
    "template_name" => "Inicio",
    "simple_fields" => [
        ["field_key" => "hero_badge", "label" => "Hero badge", "field_type" => "text", "default" => "Leading Healthcare Specialists", "default_visible" => 1],
        ["field_key" => "hero_title", "label" => "Hero título", "field_type" => "text", "default" => "Advanced Medical Care for Your Family's Health", "default_visible" => 1],
        ["field_key" => "hero_text", "label" => "Hero texto", "field_type" => "textarea", "default" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.", "default_visible" => 1],
        ["field_key" => "hero_image", "label" => "Hero imagen", "field_type" => "image", "default" => "assets/img/health/showcase-1.webp", "default_visible" => 1],
        ["field_key" => "hero_image_alt", "label" => "Hero imagen alt", "field_type" => "text", "default" => "Advanced Healthcare", "default_visible" => 1],
        ["field_key" => "hero_primary_cta_text", "label" => "Hero botón principal texto", "field_type" => "text", "default" => "Book Appointment", "default_visible" => 1],
        ["field_key" => "hero_primary_cta_link_type", "label" => "Hero botón principal tipo enlace", "field_type" => "text", "default" => "custom", "default_visible" => 1],
        ["field_key" => "hero_primary_cta_page_id", "label" => "Hero botón principal página interna", "field_type" => "text", "default" => "", "default_visible" => 1],
        ["field_key" => "hero_primary_cta_url", "label" => "Hero botón principal URL", "field_type" => "url", "default" => "appointment.php", "default_visible" => 1],
        ["field_key" => "hero_secondary_cta_text", "label" => "Hero botón secundario texto", "field_type" => "text", "default" => "Explore Services", "default_visible" => 1],
        ["field_key" => "hero_secondary_cta_link_type", "label" => "Hero botón secundario tipo enlace", "field_type" => "text", "default" => "custom", "default_visible" => 1],
        ["field_key" => "hero_secondary_cta_page_id", "label" => "Hero botón secundario página interna", "field_type" => "text", "default" => "", "default_visible" => 1],
        ["field_key" => "hero_secondary_cta_url", "label" => "Hero botón secundario URL", "field_type" => "url", "default" => "services.php", "default_visible" => 1],
        ["field_key" => "hero_emergency_label", "label" => "Hero badge 1 etiqueta", "field_type" => "text", "default" => "Emergency Line", "default_visible" => 1],
        ["field_key" => "hero_emergency_value", "label" => "Hero badge 1 valor", "field_type" => "text", "default" => "+1 (555) 987-6543", "default_visible" => 1],
        ["field_key" => "hero_hours_label", "label" => "Hero badge 2 etiqueta", "field_type" => "text", "default" => "Working Hours", "default_visible" => 1],
        ["field_key" => "hero_hours_value", "label" => "Hero badge 2 valor", "field_type" => "text", "default" => "Mon-Fri: 8AM-8PM", "default_visible" => 1],
        ["field_key" => "home_about_image", "label" => "Home About imagen", "field_type" => "image", "default" => "assets/img/health/facilities-1.webp", "default_visible" => 1],
        ["field_key" => "home_about_image_alt", "label" => "Home About imagen alt", "field_type" => "text", "default" => "Modern Healthcare Facility", "default_visible" => 1],
        ["field_key" => "home_about_experience_years", "label" => "Años de experiencia", "field_type" => "text", "default" => "25+", "default_visible" => 1],
        ["field_key" => "home_about_experience_text", "label" => "Texto de experiencia", "field_type" => "text", "default" => "Years of Excellence", "default_visible" => 1],
        ["field_key" => "home_about_title", "label" => "Título principal", "field_type" => "text", "default" => "Committed to Exceptional Patient Care", "default_visible" => 1],
        ["field_key" => "home_about_lead", "label" => "Texto introductorio", "field_type" => "textarea", "default" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.", "default_visible" => 1],
        ["field_key" => "home_about_text", "label" => "Texto complementario", "field_type" => "textarea", "default" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin consequat magna eu accumsan mattis. Duis non augue in tortor facilisis tincidunt ac sit amet sapien. Suspendisse id risus non nisi sodales condimentum.", "default_visible" => 1],
        ["field_key" => "home_about_primary_cta_text", "label" => "Home About botón principal texto", "field_type" => "text", "default" => "Learn More About Us", "default_visible" => 1],
        ["field_key" => "home_about_primary_cta_link_type", "label" => "Home About botón principal tipo enlace", "field_type" => "text", "default" => "custom", "default_visible" => 1],
        ["field_key" => "home_about_primary_cta_page_id", "label" => "Home About botón principal página interna", "field_type" => "text", "default" => "", "default_visible" => 1],
        ["field_key" => "home_about_primary_cta_url", "label" => "Home About botón principal URL", "field_type" => "url", "default" => "about.php", "default_visible" => 1],
        ["field_key" => "home_about_secondary_cta_text", "label" => "Home About botón secundario texto", "field_type" => "text", "default" => "Meet Our Team", "default_visible" => 1],
        ["field_key" => "home_about_secondary_cta_link_type", "label" => "Home About botón secundario tipo enlace", "field_type" => "text", "default" => "custom", "default_visible" => 1],
        ["field_key" => "home_about_secondary_cta_page_id", "label" => "Home About botón secundario página interna", "field_type" => "text", "default" => "", "default_visible" => 1],
        ["field_key" => "home_about_secondary_cta_url", "label" => "Home About botón secundario URL", "field_type" => "url", "default" => "#", "default_visible" => 1],
        ["field_key" => "home_about_certifications_title", "label" => "Home About certificaciones título", "field_type" => "text", "default" => "Our Accreditations", "default_visible" => 1],
        ["field_key" => "featured_departments_title", "label" => "Featured Departments título", "field_type" => "text", "default" => "Featured Departments", "default_visible" => 1],
        ["field_key" => "featured_departments_text", "label" => "Featured Departments texto", "field_type" => "textarea", "default" => "Necessitatibus eius consequatur ex aliquid fuga eum quidem sint consectetur velit", "default_visible" => 1],
        ["field_key" => "featured_services_title", "label" => "Featured Services título", "field_type" => "text", "default" => "Featured Services", "default_visible" => 1],
        ["field_key" => "featured_services_text", "label" => "Featured Services texto", "field_type" => "textarea", "default" => "Necessitatibus eius consequatur ex aliquid fuga eum quidem sint consectetur velit", "default_visible" => 1],
        ["field_key" => "find_doctor_title", "label" => "Find A Doctor título", "field_type" => "text", "default" => "Find A Doctor", "default_visible" => 1],
        ["field_key" => "find_doctor_text", "label" => "Find A Doctor texto", "field_type" => "textarea", "default" => "Necessitatibus eius consequatur ex aliquid fuga eum quidem sint consectetur velit", "default_visible" => 1],
        ["field_key" => "doctor_search_placeholder", "label" => "Buscador doctor placeholder", "field_type" => "text", "default" => "Doctor name or keyword", "default_visible" => 1],
        ["field_key" => "doctor_specialty_placeholder", "label" => "Buscador especialidad placeholder", "field_type" => "text", "default" => "Select Specialty", "default_visible" => 1],
        ["field_key" => "doctor_search_button_text", "label" => "Buscador botón texto", "field_type" => "text", "default" => "Search Doctor", "default_visible" => 1],
        ["field_key" => "cta_title", "label" => "Call To Action título", "field_type" => "text", "default" => "Your Health is Our Priority", "default_visible" => 1],
        ["field_key" => "cta_text", "label" => "Call To Action texto", "field_type" => "textarea", "default" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.", "default_visible" => 1],
        ["field_key" => "cta_primary_text", "label" => "Texto del botón", "field_type" => "text", "default" => "Book Appointment", "default_visible" => 1],
        ["field_key" => "cta_primary_link_type", "label" => "Call To Action botón principal tipo enlace", "field_type" => "text", "default" => "custom", "default_visible" => 1],
        ["field_key" => "cta_primary_page_id", "label" => "Call To Action botón principal página interna", "field_type" => "text", "default" => "", "default_visible" => 1],
        ["field_key" => "cta_primary_url", "label" => "Call To Action botón principal URL", "field_type" => "url", "default" => "appointment.php", "default_visible" => 1],
        ["field_key" => "cta_secondary_text", "label" => "Texto del botón", "field_type" => "text", "default" => "Find a Doctor", "default_visible" => 1],
        ["field_key" => "cta_secondary_link_type", "label" => "Call To Action botón secundario tipo enlace", "field_type" => "text", "default" => "custom", "default_visible" => 1],
        ["field_key" => "cta_secondary_page_id", "label" => "Call To Action botón secundario página interna", "field_type" => "text", "default" => "", "default_visible" => 1],
        ["field_key" => "cta_secondary_url", "label" => "Call To Action botón secundario URL", "field_type" => "url", "default" => "doctors.php", "default_visible" => 1],
        ["field_key" => "cta_emergency_title", "label" => "Call To Action emergencia título", "field_type" => "text", "default" => "Medical Emergency?", "default_visible" => 1],
        ["field_key" => "cta_emergency_text", "label" => "Call To Action emergencia texto", "field_type" => "textarea", "default" => "Call our 24/7 emergency hotline for immediate assistance", "default_visible" => 1],
        ["field_key" => "cta_emergency_button_text", "label" => "Call To Action emergencia botón texto", "field_type" => "text", "default" => "Call (555) 123-4567", "default_visible" => 1],
        ["field_key" => "cta_emergency_button_url", "label" => "Call To Action emergencia botón URL", "field_type" => "url", "default" => "tel:911", "default_visible" => 1],
        ["field_key" => "emergency_info_title", "label" => "Emergency Info título", "field_type" => "text", "default" => "Emergency Info", "default_visible" => 1],
        ["field_key" => "emergency_info_text", "label" => "Emergency Info texto", "field_type" => "textarea", "default" => "Necessitatibus eius consequatur ex aliquid fuga eum quidem sint consectetur velit", "default_visible" => 1],
        ["field_key" => "emergency_banner_title", "label" => "Emergency banner título", "field_type" => "text", "default" => "Medical Emergency?", "default_visible" => 1],
        ["field_key" => "emergency_banner_text", "label" => "Emergency banner texto", "field_type" => "textarea", "default" => "If you are experiencing a life-threatening emergency, call 911 immediately or go to your nearest emergency room.", "default_visible" => 1],
        ["field_key" => "emergency_banner_button_text", "label" => "Emergency banner botón texto", "field_type" => "text", "default" => "Call 911", "default_visible" => 1],
        ["field_key" => "emergency_banner_button_url", "label" => "Emergency banner botón URL", "field_type" => "url", "default" => "tel:911", "default_visible" => 1],
        ["field_key" => "quick_actions_title", "label" => "Quick Actions título", "field_type" => "text", "default" => "Quick Actions", "default_visible" => 1],
        ["field_key" => "emergency_tips_title", "label" => "Emergency Tips título", "field_type" => "text", "default" => "When to Seek Emergency Care", "default_visible" => 1],
    ],
    "repeaters" => [
        [
            "repeater_key" => "hero_features",
            "label" => "Portada - Características destacadas",
            "fields" => [
                ["field_key" => "icon_class", "label" => "Icono", "field_type" => "text", "default" => ""],
                ["field_key" => "title", "label" => "Título", "field_type" => "text", "default" => ""],
                ["field_key" => "text", "label" => "Texto", "field_type" => "text", "default" => ""],
            ],
            "items" => [
                ["item_index" => 0, "item_label" => "Característica 1", "default_visible" => 1, "defaults" => ["icon_class" => "bi bi-heart-pulse-fill", "title" => "Cardiology", "text" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit."]],
                ["item_index" => 1, "item_label" => "Característica 2", "default_visible" => 1, "defaults" => ["icon_class" => "bi bi-lungs-fill", "title" => "Pulmonology", "text" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit."]],
                ["item_index" => 2, "item_label" => "Característica 3", "default_visible" => 1, "defaults" => ["icon_class" => "bi bi-capsule", "title" => "Diagnostics", "text" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit."]],
            ],
        ],
        [
            "repeater_key" => "home_about_features",
            "label" => "Home About features",
            "fields" => [
                ["field_key" => "icon_class", "label" => "Icono", "field_type" => "text", "default" => ""],
                ["field_key" => "title", "label" => "Título", "field_type" => "text", "default" => ""],
                ["field_key" => "text", "label" => "Texto", "field_type" => "text", "default" => ""],
            ],
            "items" => [
                ["item_index" => 0, "item_label" => "Característica 1", "default_visible" => 1, "defaults" => ["icon_class" => "bi bi-heart-pulse", "title" => "Compassionate Care", "text" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit."]],
                ["item_index" => 1, "item_label" => "Característica 2", "default_visible" => 1, "defaults" => ["icon_class" => "bi bi-star", "title" => "Medical Excellence", "text" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit."]],
            ],
        ],
        [
            "repeater_key" => "home_certifications",
            "label" => "Certificaciones - Logos",
            "fields" => [
                ["field_key" => "image", "label" => "Imagen", "field_type" => "image", "default" => ""],
                ["field_key" => "alt", "label" => "Texto alternativo", "field_type" => "text", "default" => ""],
            ],
            "items" => [
                ["item_index" => 0, "item_label" => "Logo 1", "default_visible" => 1, "defaults" => ["image" => "assets/img/clients/clients-1.webp", "alt" => "Certification"]],
                ["item_index" => 1, "item_label" => "Logo 2", "default_visible" => 1, "defaults" => ["image" => "assets/img/clients/clients-2.webp", "alt" => "Certification"]],
                ["item_index" => 2, "item_label" => "Logo 3", "default_visible" => 1, "defaults" => ["image" => "assets/img/clients/clients-3.webp", "alt" => "Certification"]],
                ["item_index" => 3, "item_label" => "Logo 4", "default_visible" => 1, "defaults" => ["image" => "assets/img/clients/clients-4.webp", "alt" => "Certification"]],
            ],
        ],
        [
            "repeater_key" => "featured_departments",
            "label" => "Especialidades destacadas - tarjetas",
            "fields" => [
                ["field_key" => "image", "label" => "Imagen", "field_type" => "image", "default" => ""],
                ["field_key" => "alt", "label" => "Texto alternativo", "field_type" => "text", "default" => ""],
                ["field_key" => "icon_class", "label" => "Icono", "field_type" => "text", "default" => ""],
                ["field_key" => "title", "label" => "Título", "field_type" => "text", "default" => ""],
                ["field_key" => "text", "label" => "Texto", "field_type" => "textarea", "default" => ""],
                ["field_key" => "link_text", "label" => "Texto del enlace", "field_type" => "text", "default" => ""],
                ["field_key" => "link_type", "label" => "Tipo de enlace", "field_type" => "text", "default" => ""],
                ["field_key" => "page_id", "label" => "Página interna", "field_type" => "text", "default" => ""],
                ["field_key" => "link_url", "label" => "URL personalizada", "field_type" => "url", "default" => ""],
            ],
            "items" => [
                ["item_index" => 0, "item_label" => "Especialidad 1", "default_visible" => 1, "defaults" => ["image" => "assets/img/health/cardiology-3.webp", "alt" => "Cardiology Department", "icon_class" => "fas fa-heartbeat", "title" => "Cardiology", "text" => "Comprehensive cardiovascular care with advanced diagnostic techniques and treatment options for heart conditions, ensuring optimal cardiac health for all patients.", "link_text" => "Learn More", "link_type" => "custom", "page_id" => "", "link_url" => "department-details.php"]],
                ["item_index" => 1, "item_label" => "Especialidad 2", "default_visible" => 1, "defaults" => ["image" => "assets/img/health/neurology-2.webp", "alt" => "Neurology Department", "icon_class" => "fas fa-brain", "title" => "Neurology", "text" => "Expert neurological care specializing in brain and nervous system disorders, providing cutting-edge treatments and compassionate support for neurological conditions.", "link_text" => "Learn More", "link_type" => "custom", "page_id" => "", "link_url" => "department-details.php"]],
                ["item_index" => 2, "item_label" => "Especialidad 3", "default_visible" => 1, "defaults" => ["image" => "assets/img/health/orthopedics-4.webp", "alt" => "Orthopedics Department", "icon_class" => "fas fa-bone", "title" => "Orthopedics", "text" => "Advanced musculoskeletal care focusing on bones, joints, and muscles with innovative surgical and non-surgical treatment approaches for mobility restoration.", "link_text" => "Learn More", "link_type" => "custom", "page_id" => "", "link_url" => "department-details.php"]],
                ["item_index" => 3, "item_label" => "Especialidad 4", "default_visible" => 1, "defaults" => ["image" => "assets/img/health/pediatrics-3.webp", "alt" => "Pediatrics Department", "icon_class" => "fas fa-baby", "title" => "Pediatrics", "text" => "Specialized healthcare for children from infancy through adolescence, offering comprehensive medical care in a child-friendly environment with experienced pediatric specialists.", "link_text" => "Learn More", "link_type" => "custom", "page_id" => "", "link_url" => "department-details.php"]],
                ["item_index" => 4, "item_label" => "Especialidad 5", "default_visible" => 1, "defaults" => ["image" => "assets/img/health/oncology-4.webp", "alt" => "Oncology Department", "icon_class" => "fas fa-shield-alt", "title" => "Oncology", "text" => "Comprehensive cancer care with multidisciplinary approach, offering advanced treatment options, clinical trials, and compassionate support throughout the cancer journey.", "link_text" => "Learn More", "link_type" => "custom", "page_id" => "", "link_url" => "department-details.php"]],
                ["item_index" => 5, "item_label" => "Especialidad 6", "default_visible" => 1, "defaults" => ["image" => "assets/img/health/emergency-2.webp", "alt" => "Emergency Department", "icon_class" => "fas fa-ambulance", "title" => "Emergency Care", "text" => "Round-the-clock emergency medical services with rapid response capabilities, state-of-the-art equipment, and experienced emergency physicians for critical care.", "link_text" => "Learn More", "link_type" => "custom", "page_id" => "", "link_url" => "department-details.php"]],
            ],
        ],
        [
            "repeater_key" => "featured_services",
            "label" => "Servicios destacados - tarjetas",
            "fields" => [
                ["field_key" => "icon_class", "label" => "Icono", "field_type" => "text", "default" => ""],
                ["field_key" => "title", "label" => "Título", "field_type" => "text", "default" => ""],
                ["field_key" => "text", "label" => "Texto", "field_type" => "textarea", "default" => ""],
                ["field_key" => "feature_1", "label" => "Característica 1", "field_type" => "text", "default" => ""],
                ["field_key" => "feature_2", "label" => "Característica 2", "field_type" => "text", "default" => ""],
                ["field_key" => "feature_3", "label" => "Característica 3", "field_type" => "text", "default" => ""],
                ["field_key" => "link_text", "label" => "Texto del enlace", "field_type" => "text", "default" => ""],
                ["field_key" => "link_type", "label" => "Tipo de enlace", "field_type" => "text", "default" => ""],
                ["field_key" => "page_id", "label" => "Página interna", "field_type" => "text", "default" => ""],
                ["field_key" => "link_url", "label" => "URL del enlace", "field_type" => "url", "default" => ""],
            ],
            "items" => [
                ["item_index" => 0, "item_label" => "Servicio 1", "default_visible" => 1, "defaults" => ["icon_class" => "fas fa-heartbeat", "title" => "Cardiology Excellence", "text" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.", "feature_1" => "Advanced Heart Surgery", "feature_2" => "24/7 Emergency Care", "feature_3" => "Preventive Screenings", "link_text" => "Learn More", "link_url" => "services.php"]],
                ["item_index" => 1, "item_label" => "Servicio 2", "default_visible" => 1, "defaults" => ["icon_class" => "fas fa-brain", "title" => "Neurology & Brain Health", "text" => "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse.", "feature_1" => "Brain Imaging & Diagnostics", "feature_2" => "Stroke Treatment Center", "feature_3" => "Neurological Rehabilitation", "link_text" => "Learn More", "link_url" => "services.php"]],
                ["item_index" => 2, "item_label" => "Servicio 3", "default_visible" => 1, "defaults" => ["icon_class" => "fas fa-bone", "title" => "Orthopedic Surgery", "text" => "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Sed ut perspiciatis unde omnis iste natus error.", "feature_1" => "Joint Replacement Surgery", "feature_2" => "Sports Medicine", "feature_3" => "Minimally Invasive Procedures", "link_text" => "Learn More", "link_url" => "services.php"]],
                ["item_index" => 3, "item_label" => "Servicio 4", "default_visible" => 1, "defaults" => ["icon_class" => "fas fa-ambulance", "title" => "Emergency & Trauma Care", "text" => "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.", "feature_1" => "24/7 Emergency Department", "feature_2" => "Level 1 Trauma Center", "feature_3" => "Critical Care Units", "link_text" => "Learn More", "link_url" => "services.php"]],
            ],
        ],
        [
            "repeater_key" => "featured_doctors",
            "label" => "Featured Doctors cards",
            "fields" => [
                ["field_key" => "image", "label" => "Imagen", "field_type" => "image", "default" => ""],
                ["field_key" => "alt", "label" => "Texto alternativo", "field_type" => "text", "default" => ""],
                ["field_key" => "availability_status", "label" => "Estado de disponibilidad", "field_type" => "text", "default" => ""],
                ["field_key" => "availability_text", "label" => "Texto de disponibilidad", "field_type" => "text", "default" => ""],
                ["field_key" => "name", "label" => "Nombre", "field_type" => "text", "default" => ""],
                ["field_key" => "specialty", "label" => "Especialidad", "field_type" => "text", "default" => ""],
                ["field_key" => "experience", "label" => "Experiencia", "field_type" => "text", "default" => ""],
                ["field_key" => "rating", "label" => "Rating", "field_type" => "text", "default" => ""],
                ["field_key" => "profile_button_text", "label" => "Botón perfil texto", "field_type" => "text", "default" => ""],
                ["field_key" => "profile_button_url", "label" => "Botón perfil URL", "field_type" => "url", "default" => ""],
                ["field_key" => "appointment_button_text", "label" => "Botón cita texto", "field_type" => "text", "default" => ""],
                ["field_key" => "appointment_button_url", "label" => "Botón cita URL", "field_type" => "url", "default" => ""],
            ],
            "items" => [
                ["item_index" => 0, "item_label" => "Doctor 1", "default_visible" => 1, "defaults" => ["image" => "assets/img/health/staff-3.webp", "alt" => "Dr. Sarah Mitchell", "availability_status" => "online", "availability_text" => "Available", "name" => "Dr. Sarah Mitchell", "specialty" => "Cardiology", "experience" => "15+ years experience", "rating" => "(4.9)", "profile_button_text" => "View Profile", "profile_button_url" => "#", "appointment_button_text" => "Book Appointment", "appointment_button_url" => "#"]],
                ["item_index" => 1, "item_label" => "Doctor 2", "default_visible" => 1, "defaults" => ["image" => "assets/img/health/staff-7.webp", "alt" => "Dr. Michael Rodriguez", "availability_status" => "busy", "availability_text" => "In Surgery", "name" => "Dr. Michael Rodriguez", "specialty" => "Neurology", "experience" => "12+ years experience", "rating" => "(4.7)", "profile_button_text" => "View Profile", "profile_button_url" => "#", "appointment_button_text" => "Book Appointment", "appointment_button_url" => "#"]],
                ["item_index" => 2, "item_label" => "Doctor 3", "default_visible" => 1, "defaults" => ["image" => "assets/img/health/staff-1.webp", "alt" => "Dr. Emily Chen", "availability_status" => "online", "availability_text" => "Available", "name" => "Dr. Emily Chen", "specialty" => "Pediatrics", "experience" => "8+ years experience", "rating" => "(5.0)", "profile_button_text" => "View Profile", "profile_button_url" => "#", "appointment_button_text" => "Book Appointment", "appointment_button_url" => "#"]],
                ["item_index" => 3, "item_label" => "Doctor 4", "default_visible" => 1, "defaults" => ["image" => "assets/img/health/staff-9.webp", "alt" => "Dr. James Thompson", "availability_status" => "offline", "availability_text" => "Next: Tomorrow 9AM", "name" => "Dr. James Thompson", "specialty" => "Orthopedics", "experience" => "20+ years experience", "rating" => "(4.8)", "profile_button_text" => "View Profile", "profile_button_url" => "#", "appointment_button_text" => "Book Appointment", "appointment_button_url" => "#"]],
                ["item_index" => 4, "item_label" => "Doctor 5", "default_visible" => 1, "defaults" => ["image" => "assets/img/health/staff-5.webp", "alt" => "Dr. Lisa Anderson", "availability_status" => "online", "availability_text" => "Available", "name" => "Dr. Lisa Anderson", "specialty" => "Dermatology", "experience" => "10+ years experience", "rating" => "(4.6)", "profile_button_text" => "View Profile", "profile_button_url" => "#", "appointment_button_text" => "Book Appointment", "appointment_button_url" => "#"]],
                ["item_index" => 5, "item_label" => "Doctor 6", "default_visible" => 1, "defaults" => ["image" => "assets/img/health/staff-12.webp", "alt" => "Dr. Robert Kim", "availability_status" => "online", "availability_text" => "Available", "name" => "Dr. Robert Kim", "specialty" => "Oncology", "experience" => "18+ years experience", "rating" => "(4.9)", "profile_button_text" => "View Profile", "profile_button_url" => "#", "appointment_button_text" => "Book Appointment", "appointment_button_url" => "#"]],
            ],
        ],
        [
            "repeater_key" => "cta_features",
            "label" => "Call To Action features",
            "fields" => [
                ["field_key" => "icon_class", "label" => "Icono", "field_type" => "text", "default" => ""],
                ["field_key" => "title", "label" => "Título", "field_type" => "text", "default" => ""],
                ["field_key" => "text", "label" => "Texto", "field_type" => "text", "default" => ""],
                ["field_key" => "link_text", "label" => "Texto del enlace", "field_type" => "text", "default" => ""],
                ["field_key" => "link_url", "label" => "URL del enlace", "field_type" => "url", "default" => ""],
            ],
            "items" => [
                ["item_index" => 0, "item_label" => "Característica 1", "default_visible" => 1, "defaults" => ["icon_class" => "bi bi-heart-pulse", "title" => "24/7 Emergency Care", "text" => "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.", "link_text" => "Learn More", "link_url" => "#"]],
                ["item_index" => 1, "item_label" => "Característica 2", "default_visible" => 1, "defaults" => ["icon_class" => "bi bi-calendar-check", "title" => "Easy Online Booking", "text" => "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.", "link_text" => "Book Now", "link_url" => "#"]],
                ["item_index" => 2, "item_label" => "Característica 3", "default_visible" => 1, "defaults" => ["icon_class" => "bi bi-people", "title" => "Expert Medical Team", "text" => "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim.", "link_text" => "Meet Our Doctors", "link_url" => "#"]],
            ],
        ],
        [
            "repeater_key" => "emergency_contacts",
            "label" => "Emergency contacts",
            "fields" => [
                ["field_key" => "variant", "label" => "Variante", "field_type" => "text", "default" => ""],
                ["field_key" => "icon_class", "label" => "Icono", "field_type" => "text", "default" => ""],
                ["field_key" => "title", "label" => "Título", "field_type" => "text", "default" => ""],
                ["field_key" => "phone", "label" => "Teléfono", "field_type" => "text", "default" => ""],
                ["field_key" => "address", "label" => "Dirección", "field_type" => "text", "default" => ""],
                ["field_key" => "description", "label" => "Descripción", "field_type" => "text", "default" => ""],
                ["field_key" => "hours", "label" => "Horario", "field_type" => "text", "default" => ""],
                ["field_key" => "button_text", "label" => "Texto del botón", "field_type" => "text", "default" => ""],
                ["field_key" => "button_url", "label" => "URL del botón", "field_type" => "url", "default" => ""],
            ],
            "items" => [
                ["item_index" => 0, "item_label" => "Contact 1", "default_visible" => 1, "defaults" => ["variant" => "urgent", "icon_class" => "bi bi-hospital", "title" => "Emergency Room", "phone" => "+1 (555) 123-4567", "address" => "1245 Healthcare Blvd, Medical City, CA 90210", "description" => "", "hours" => "Open 24/7", "button_text" => "Call Now", "button_url" => "tel:+15551234567"]],
                ["item_index" => 1, "item_label" => "Contact 2", "default_visible" => 1, "defaults" => ["variant" => "", "icon_class" => "bi bi-clock", "title" => "Urgent Care", "phone" => "+1 (555) 987-6543", "address" => "892 Wellness Ave, Health District, CA 90211", "description" => "", "hours" => "Mon-Sun: 7:00 AM - 10:00 PM", "button_text" => "Call Now", "button_url" => "tel:+15559876543"]],
                ["item_index" => 2, "item_label" => "Contact 3", "default_visible" => 1, "defaults" => ["variant" => "", "icon_class" => "bi bi-headset", "title" => "Nurse Helpline", "phone" => "+1 (555) 456-7890", "address" => "", "description" => "24/7 medical advice and guidance", "hours" => "Available 24/7", "button_text" => "Call Now", "button_url" => "tel:+15554567890"]],
                ["item_index" => 3, "item_label" => "Contact 4", "default_visible" => 1, "defaults" => ["variant" => "", "icon_class" => "bi bi-heart-pulse", "title" => "Poison Control", "phone" => "1-800-222-1222", "address" => "", "description" => "National poison control hotline", "hours" => "Available 24/7", "button_text" => "Call Now", "button_url" => "tel:18002221222"]],
            ],
        ],
        [
            "repeater_key" => "quick_actions",
            "label" => "Quick Actions",
            "fields" => [
                ["field_key" => "icon_class", "label" => "Icono", "field_type" => "text", "default" => ""],
                ["field_key" => "label", "label" => "Etiqueta", "field_type" => "text", "default" => ""],
                ["field_key" => "url", "label" => "URL", "field_type" => "url", "default" => ""],
            ],
            "items" => [
                ["item_index" => 0, "item_label" => "Action 1", "default_visible" => 1, "defaults" => ["icon_class" => "bi bi-geo-alt-fill", "label" => "Get Directions", "url" => "#"]],
                ["item_index" => 1, "item_label" => "Action 2", "default_visible" => 1, "defaults" => ["icon_class" => "bi bi-calendar-check", "label" => "Book Appointment", "url" => "#"]],
                ["item_index" => 2, "item_label" => "Action 3", "default_visible" => 1, "defaults" => ["icon_class" => "bi bi-person-badge", "label" => "Find a Doctor", "url" => "#"]],
                ["item_index" => 3, "item_label" => "Action 4", "default_visible" => 1, "defaults" => ["icon_class" => "bi bi-chat-dots", "label" => "Live Chat", "url" => "#"]],
            ],
        ],
        [
            "repeater_key" => "emergency_tips",
            "label" => "Emergency Tips",
            "fields" => [
                ["field_key" => "text", "label" => "Texto", "field_type" => "text", "default" => ""],
            ],
            "items" => [
                ["item_index" => 0, "item_label" => "Tip 1", "default_visible" => 1, "defaults" => ["text" => "Chest pain or difficulty breathing"]],
                ["item_index" => 1, "item_label" => "Tip 2", "default_visible" => 1, "defaults" => ["text" => "Severe allergic reactions"]],
                ["item_index" => 2, "item_label" => "Tip 3", "default_visible" => 1, "defaults" => ["text" => "Major trauma or injuries"]],
                ["item_index" => 3, "item_label" => "Tip 4", "default_visible" => 1, "defaults" => ["text" => "Signs of stroke or heart attack"]],
                ["item_index" => 4, "item_label" => "Tip 5", "default_visible" => 1, "defaults" => ["text" => "Severe burns or bleeding"]],
                ["item_index" => 5, "item_label" => "Tip 6", "default_visible" => 1, "defaults" => ["text" => "Loss of consciousness"]],
                ["item_index" => 6, "item_label" => "Tip 7", "default_visible" => 1, "defaults" => ["text" => "Severe abdominal pain"]],
                ["item_index" => 7, "item_label" => "Tip 8", "default_visible" => 1, "defaults" => ["text" => "High fever with confusion"]],
            ],
        ],
    ],
];
