<?php

return [
    "template_key" => "privacy",
    "template_name" => "Política de privacidad",
    "simple_fields" => [
        ["field_key" => "hero_title", "label" => "Titulo principal", "field_type" => "text", "default" => "Privacy", "default_visible" => 1],
        ["field_key" => "hero_subtitle", "label" => "Subtitulo principal", "field_type" => "textarea", "default" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.", "default_visible" => 1],
        ["field_key" => "effective_date", "label" => "Fecha efectiva", "field_type" => "text", "default" => "Effective Date: February 27, 2025", "default_visible" => 1],
        ["field_key" => "policy_title", "label" => "Politica titulo", "field_type" => "text", "default" => "Privacy Policy", "default_visible" => 1],
        ["field_key" => "policy_intro", "label" => "Politica intro", "field_type" => "textarea", "default" => "This Privacy Policy describes how we collect, use, process, and disclose your information, including personal information, in conjunction with your access to and use of our services.", "default_visible" => 1],
        ["field_key" => "intro_title", "label" => "Introduccion titulo", "field_type" => "text", "default" => "1. Introduction", "default_visible" => 1],
        ["field_key" => "intro_text_1", "label" => "Introduccion texto 1", "field_type" => "textarea", "default" => "When you use our services, you're trusting us with your information. We understand this is a big responsibility and work hard to protect your information and put you in control.", "default_visible" => 1],
        ["field_key" => "intro_text_2", "label" => "Introduccion texto 2", "field_type" => "textarea", "default" => "This Privacy Policy is meant to help you understand what information we collect, why we collect it, and how you can update, manage, export, and delete your information.", "default_visible" => 1],
        ["field_key" => "collection_title", "label" => "Collection titulo", "field_type" => "text", "default" => "2. Information We Collect", "default_visible" => 1],
        ["field_key" => "collection_text", "label" => "Collection texto", "field_type" => "textarea", "default" => "We collect information to provide better services to our users. The types of information we collect include:", "default_visible" => 1],
        ["field_key" => "provided_title", "label" => "Provided titulo", "field_type" => "text", "default" => "2.1 Information You Provide", "default_visible" => 1],
        ["field_key" => "provided_text", "label" => "Provided texto", "field_type" => "textarea", "default" => "When you create an account or use our services, you provide us with personal information that includes:", "default_visible" => 1],
        ["field_key" => "automatic_title", "label" => "Automatic titulo", "field_type" => "text", "default" => "2.2 Automatic Information", "default_visible" => 1],
        ["field_key" => "automatic_text", "label" => "Automatic texto", "field_type" => "textarea", "default" => "We automatically collect and store certain information when you use our services:", "default_visible" => 1],
        ["field_key" => "use_title", "label" => "Use titulo", "field_type" => "text", "default" => "3. How We Use Your Information", "default_visible" => 1],
        ["field_key" => "use_text", "label" => "Use texto", "field_type" => "textarea", "default" => "We use the information we collect to provide, maintain, and improve our services. Specifically, we use your information to:", "default_visible" => 1],
        ["field_key" => "sharing_title", "label" => "Sharing titulo", "field_type" => "text", "default" => "4. Information Sharing and Disclosure", "default_visible" => 1],
        ["field_key" => "sharing_text", "label" => "Sharing texto", "field_type" => "textarea", "default" => "We do not share personal information with companies, organizations, or individuals outside of our company except in the following cases:", "default_visible" => 1],
        ["field_key" => "consent_title", "label" => "Consent titulo", "field_type" => "text", "default" => "4.1 With Your Consent", "default_visible" => 1],
        ["field_key" => "consent_text", "label" => "Consent texto", "field_type" => "textarea", "default" => "We will share personal information with companies, organizations, or individuals outside of our company when we have your consent to do so.", "default_visible" => 1],
        ["field_key" => "legal_title", "label" => "Legal titulo", "field_type" => "text", "default" => "4.2 For Legal Reasons", "default_visible" => 1],
        ["field_key" => "legal_text", "label" => "Legal texto", "field_type" => "textarea", "default" => "We will share personal information if we have a good-faith belief that access, use, preservation, or disclosure of the information is reasonably necessary to:", "default_visible" => 1],
        ["field_key" => "security_title", "label" => "Security titulo", "field_type" => "text", "default" => "5. Data Security", "default_visible" => 1],
        ["field_key" => "security_text", "label" => "Security texto", "field_type" => "textarea", "default" => "We work hard to protect our users from unauthorized access to or unauthorized alteration, disclosure, or destruction of information we hold. In particular:", "default_visible" => 1],
        ["field_key" => "rights_title", "label" => "Rights titulo", "field_type" => "text", "default" => "6. Your Rights and Choices", "default_visible" => 1],
        ["field_key" => "rights_text", "label" => "Rights texto", "field_type" => "textarea", "default" => "You have certain rights regarding your personal information, including:", "default_visible" => 1],
        ["field_key" => "updates_title", "label" => "Updates titulo", "field_type" => "text", "default" => "7. Changes to This Policy", "default_visible" => 1],
        ["field_key" => "updates_text_1", "label" => "Updates texto 1", "field_type" => "textarea", "default" => "We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the effective date at the top.", "default_visible" => 1],
        ["field_key" => "updates_text_2", "label" => "Updates texto 2", "field_type" => "textarea", "default" => "Your continued use of our services after any changes to this Privacy Policy constitutes your acceptance of such changes.", "default_visible" => 1],
        ["field_key" => "contact_title", "label" => "Contacto titulo", "field_type" => "text", "default" => "Contact Us", "default_visible" => 1],
        ["field_key" => "contact_text", "label" => "Contacto texto", "field_type" => "textarea", "default" => "If you have any questions about this Privacy Policy or our practices, please contact us:", "default_visible" => 1],
        ["field_key" => "contact_email_label", "label" => "Contacto email label", "field_type" => "text", "default" => "Email:", "default_visible" => 1],
        ["field_key" => "contact_email", "label" => "Contacto email", "field_type" => "text", "default" => "privacy@example.com", "default_visible" => 1],
        ["field_key" => "contact_address_label", "label" => "Contacto direccion label", "field_type" => "text", "default" => "Address:", "default_visible" => 1],
        ["field_key" => "contact_address", "label" => "Contacto direccion", "field_type" => "text", "default" => "123 Privacy Street, Security City, 12345", "default_visible" => 1],
    ],
    "repeaters" => [
        [
            "repeater_key" => "provided_items",
            "label" => "Provided items",
            "fields" => [["field_key" => "text", "label" => "Texto", "field_type" => "text", "default" => ""]],
            "items" => [
                ["item_index" => 0, "item_label" => "Your name and contact information", "default_visible" => 1, "defaults" => ["text" => "Your name and contact information"]],
                ["item_index" => 1, "item_label" => "Account credentials", "default_visible" => 1, "defaults" => ["text" => "Account credentials"]],
                ["item_index" => 2, "item_label" => "Payment information when required", "default_visible" => 1, "defaults" => ["text" => "Payment information when required"]],
                ["item_index" => 3, "item_label" => "Communication preferences", "default_visible" => 1, "defaults" => ["text" => "Communication preferences"]],
            ],
        ],
        [
            "repeater_key" => "automatic_items",
            "label" => "Automatic items",
            "fields" => [["field_key" => "text", "label" => "Texto", "field_type" => "text", "default" => ""]],
            "items" => [
                ["item_index" => 0, "item_label" => "Device information and identifiers", "default_visible" => 1, "defaults" => ["text" => "Device information and identifiers"]],
                ["item_index" => 1, "item_label" => "Log information and usage statistics", "default_visible" => 1, "defaults" => ["text" => "Log information and usage statistics"]],
                ["item_index" => 2, "item_label" => "Location information when enabled", "default_visible" => 1, "defaults" => ["text" => "Location information when enabled"]],
                ["item_index" => 3, "item_label" => "Browser type and settings", "default_visible" => 1, "defaults" => ["text" => "Browser type and settings"]],
            ],
        ],
        [
            "repeater_key" => "use_items",
            "label" => "Use items",
            "fields" => [["field_key" => "text", "label" => "Texto", "field_type" => "text", "default" => ""]],
            "items" => [
                ["item_index" => 0, "item_label" => "Provide and personalize our services", "default_visible" => 1, "defaults" => ["text" => "Provide and personalize our services"]],
                ["item_index" => 1, "item_label" => "Process transactions and send related information", "default_visible" => 1, "defaults" => ["text" => "Process transactions and send related information"]],
                ["item_index" => 2, "item_label" => "Send notifications and updates about our services", "default_visible" => 1, "defaults" => ["text" => "Send notifications and updates about our services"]],
                ["item_index" => 3, "item_label" => "Maintain security and verify identity", "default_visible" => 1, "defaults" => ["text" => "Maintain security and verify identity"]],
                ["item_index" => 4, "item_label" => "Analyze and improve our services", "default_visible" => 1, "defaults" => ["text" => "Analyze and improve our services"]],
            ],
        ],
        [
            "repeater_key" => "legal_items",
            "label" => "Legal items",
            "fields" => [["field_key" => "text", "label" => "Texto", "field_type" => "text", "default" => ""]],
            "items" => [
                ["item_index" => 0, "item_label" => "Meet any applicable law, regulation, legal process, or enforceable governmental request", "default_visible" => 1, "defaults" => ["text" => "Meet any applicable law, regulation, legal process, or enforceable governmental request"]],
                ["item_index" => 1, "item_label" => "Enforce applicable Terms of Service", "default_visible" => 1, "defaults" => ["text" => "Enforce applicable Terms of Service"]],
                ["item_index" => 2, "item_label" => "Detect, prevent, or otherwise address fraud, security, or technical issues", "default_visible" => 1, "defaults" => ["text" => "Detect, prevent, or otherwise address fraud, security, or technical issues"]],
                ["item_index" => 3, "item_label" => "Protect against harm to the rights, property, or safety of our users", "default_visible" => 1, "defaults" => ["text" => "Protect against harm to the rights, property, or safety of our users"]],
            ],
        ],
        [
            "repeater_key" => "security_items",
            "label" => "Security items",
            "fields" => [["field_key" => "text", "label" => "Texto", "field_type" => "text", "default" => ""]],
            "items" => [
                ["item_index" => 0, "item_label" => "We encrypt our services using SSL", "default_visible" => 1, "defaults" => ["text" => "We encrypt our services using SSL"]],
                ["item_index" => 1, "item_label" => "We review our information collection, storage, and processing practices", "default_visible" => 1, "defaults" => ["text" => "We review our information collection, storage, and processing practices"]],
                ["item_index" => 2, "item_label" => "We restrict access to personal information to employees who need that information", "default_visible" => 1, "defaults" => ["text" => "We restrict access to personal information to employees who need that information"]],
            ],
        ],
        [
            "repeater_key" => "rights_items",
            "label" => "Rights items",
            "fields" => [["field_key" => "text", "label" => "Texto", "field_type" => "text", "default" => ""]],
            "items" => [
                ["item_index" => 0, "item_label" => "The right to access your personal information", "default_visible" => 1, "defaults" => ["text" => "The right to access your personal information"]],
                ["item_index" => 1, "item_label" => "The right to correct inaccurate information", "default_visible" => 1, "defaults" => ["text" => "The right to correct inaccurate information"]],
                ["item_index" => 2, "item_label" => "The right to request deletion of your information", "default_visible" => 1, "defaults" => ["text" => "The right to request deletion of your information"]],
                ["item_index" => 3, "item_label" => "The right to restrict or object to our processing of your information", "default_visible" => 1, "defaults" => ["text" => "The right to restrict or object to our processing of your information"]],
            ],
        ],
    ],
];
