<?php

return [
    "template_key" => "services",
    "template_name" => "Servicios",
    "simple_fields" => [
        ["field_key" => "hero_title", "label" => "Titulo principal", "field_type" => "text", "default" => "Services", "default_visible" => 1],
        ["field_key" => "hero_subtitle", "label" => "Subtitulo principal", "field_type" => "textarea", "default" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.", "default_visible" => 1],
        ["field_key" => "cta_icon", "label" => "CTA icono", "field_type" => "text", "default" => "fa fa-calendar-check", "default_visible" => 1],
        ["field_key" => "cta_title", "label" => "CTA titulo", "field_type" => "text", "default" => "Ready to Schedule Your Appointment?", "default_visible" => 1],
        ["field_key" => "cta_text", "label" => "CTA texto", "field_type" => "textarea", "default" => "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur excepteur sint occaecat cupidatat non proident.", "default_visible" => 1],
        ["field_key" => "cta_primary_text", "label" => "CTA boton principal texto", "field_type" => "text", "default" => "Book Now", "default_visible" => 1],
        ["field_key" => "cta_primary_url", "label" => "CTA boton principal URL", "field_type" => "url", "default" => "appointment.html", "default_visible" => 1],
        ["field_key" => "cta_secondary_text", "label" => "CTA boton secundario texto", "field_type" => "text", "default" => "Contact Us", "default_visible" => 1],
        ["field_key" => "cta_secondary_url", "label" => "CTA boton secundario URL", "field_type" => "url", "default" => "contact.html", "default_visible" => 1],
    ],
    "repeaters" => [
        [
            "repeater_key" => "service_categories",
            "label" => "Servicios - categorias",
            "fields" => [
                ["field_key" => "category_key", "label" => "Clave del tab", "field_type" => "text", "default" => ""],
                ["field_key" => "label", "label" => "Texto del tab", "field_type" => "text", "default" => ""],
            ],
            "items" => [
                ["item_index" => 0, "item_label" => "Primary Care", "default_visible" => 1, "defaults" => ["category_key" => "primary", "label" => "Primary Care"]],
                ["item_index" => 1, "item_label" => "Specialty Care", "default_visible" => 1, "defaults" => ["category_key" => "specialty", "label" => "Specialty Care"]],
                ["item_index" => 2, "item_label" => "Diagnostics", "default_visible" => 1, "defaults" => ["category_key" => "diagnostics", "label" => "Diagnostics"]],
                ["item_index" => 3, "item_label" => "Emergency", "default_visible" => 1, "defaults" => ["category_key" => "emergency", "label" => "Emergency"]],
            ],
        ],
        [
            "repeater_key" => "services",
            "label" => "Servicios - items",
            "fields" => [
                ["field_key" => "category_key", "label" => "Clave del tab", "field_type" => "text", "default" => ""],
                ["field_key" => "column_class", "label" => "Clase de columna", "field_type" => "text", "default" => "col-lg-6"],
                ["field_key" => "variant_class", "label" => "Clase visual", "field_type" => "text", "default" => ""],
                ["field_key" => "icon_class", "label" => "Icono", "field_type" => "text", "default" => ""],
                ["field_key" => "title", "label" => "Titulo", "field_type" => "text", "default" => ""],
                ["field_key" => "description", "label" => "Descripcion", "field_type" => "textarea", "default" => ""],
                ["field_key" => "benefit_1", "label" => "Beneficio 1", "field_type" => "text", "default" => ""],
                ["field_key" => "benefit_2", "label" => "Beneficio 2", "field_type" => "text", "default" => ""],
                ["field_key" => "benefit_3", "label" => "Beneficio 3", "field_type" => "text", "default" => ""],
                ["field_key" => "benefit_4", "label" => "Beneficio 4", "field_type" => "text", "default" => ""],
                ["field_key" => "link_text", "label" => "Texto del enlace", "field_type" => "text", "default" => ""],
                ["field_key" => "link_type", "label" => "Tipo de enlace", "field_type" => "text", "default" => "custom"],
                ["field_key" => "page_id", "label" => "Pagina interna", "field_type" => "text", "default" => ""],
                ["field_key" => "link_url", "label" => "URL del enlace", "field_type" => "url", "default" => ""],
                ["field_key" => "emergency_button_text", "label" => "Boton emergencia texto", "field_type" => "text", "default" => ""],
                ["field_key" => "emergency_button_icon", "label" => "Boton emergencia icono", "field_type" => "text", "default" => ""],
                ["field_key" => "emergency_button_link_type", "label" => "Tipo de enlace", "field_type" => "text", "default" => "custom"],
                ["field_key" => "emergency_button_page_id", "label" => "Pagina interna", "field_type" => "text", "default" => ""],
                ["field_key" => "emergency_button_url", "label" => "Boton emergencia URL", "field_type" => "url", "default" => ""],
                ["field_key" => "directions_button_text", "label" => "Boton direcciones texto", "field_type" => "text", "default" => ""],
                ["field_key" => "directions_button_icon", "label" => "Boton direcciones icono", "field_type" => "text", "default" => ""],
                ["field_key" => "directions_button_link_type", "label" => "Tipo de enlace", "field_type" => "text", "default" => "custom"],
                ["field_key" => "directions_button_page_id", "label" => "Pagina interna", "field_type" => "text", "default" => ""],
                ["field_key" => "directions_button_url", "label" => "Boton direcciones URL", "field_type" => "url", "default" => ""],
            ],
            "items" => [
                ["item_index" => 0, "item_label" => "General Consultation", "default_visible" => 1, "defaults" => ["category_key" => "primary", "column_class" => "col-lg-6", "variant_class" => "", "icon_class" => "fa fa-stethoscope", "title" => "General Consultation", "description" => "Cupiditate placeat facere. Delectus quisquam et consequatur laborum sunt consectetur.", "benefit_1" => "Comprehensive Health Assessment", "benefit_2" => "Preventive Care Planning", "benefit_3" => "Health Monitoring", "benefit_4" => "", "link_text" => "Learn More", "link_url" => "service-details.html", "emergency_button_text" => "", "emergency_button_icon" => "", "emergency_button_url" => "", "directions_button_text" => "", "directions_button_icon" => "", "directions_button_url" => ""]],
                ["item_index" => 1, "item_label" => "Vaccination Services", "default_visible" => 1, "defaults" => ["category_key" => "primary", "column_class" => "col-lg-6", "variant_class" => "", "icon_class" => "fa fa-syringe", "title" => "Vaccination Services", "description" => "Voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut.", "benefit_1" => "Adult Immunizations", "benefit_2" => "Travel Vaccines", "benefit_3" => "Flu Shots", "benefit_4" => "", "link_text" => "Learn More", "link_url" => "service-details.html", "emergency_button_text" => "", "emergency_button_icon" => "", "emergency_button_url" => "", "directions_button_text" => "", "directions_button_icon" => "", "directions_button_url" => ""]],
                ["item_index" => 2, "item_label" => "Maternal Health", "default_visible" => 1, "defaults" => ["category_key" => "primary", "column_class" => "col-lg-6", "variant_class" => "", "icon_class" => "fa fa-baby", "title" => "Maternal Health", "description" => "Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore.", "benefit_1" => "Prenatal Care", "benefit_2" => "Delivery Support", "benefit_3" => "Postnatal Care", "benefit_4" => "", "link_text" => "Learn More", "link_url" => "service-details.html", "emergency_button_text" => "", "emergency_button_icon" => "", "emergency_button_url" => "", "directions_button_text" => "", "directions_button_icon" => "", "directions_button_url" => ""]],
                ["item_index" => 3, "item_label" => "Family Medicine", "default_visible" => 1, "defaults" => ["category_key" => "primary", "column_class" => "col-lg-6", "variant_class" => "", "icon_class" => "fa fa-user-md", "title" => "Family Medicine", "description" => "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus.", "benefit_1" => "All-Age Care", "benefit_2" => "Chronic Disease Management", "benefit_3" => "Wellness Programs", "benefit_4" => "", "link_text" => "Learn More", "link_url" => "service-details.html", "emergency_button_text" => "", "emergency_button_icon" => "", "emergency_button_url" => "", "directions_button_text" => "", "directions_button_icon" => "", "directions_button_url" => ""]],
                ["item_index" => 4, "item_label" => "Cardiology", "default_visible" => 1, "defaults" => ["category_key" => "specialty", "column_class" => "col-lg-6", "variant_class" => "featured", "icon_class" => "fa fa-heartbeat", "title" => "Cardiology", "description" => "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium.", "benefit_1" => "Heart Disease Treatment", "benefit_2" => "Cardiac Surgery", "benefit_3" => "Rehabilitation Programs", "benefit_4" => "", "link_text" => "Learn More", "link_url" => "service-details.html", "emergency_button_text" => "", "emergency_button_icon" => "", "emergency_button_url" => "", "directions_button_text" => "", "directions_button_icon" => "", "directions_button_url" => ""]],
                ["item_index" => 5, "item_label" => "Neurology", "default_visible" => 1, "defaults" => ["category_key" => "specialty", "column_class" => "col-lg-6", "variant_class" => "", "icon_class" => "fa fa-brain", "title" => "Neurology", "description" => "Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet consectetur.", "benefit_1" => "Neurological Assessment", "benefit_2" => "Stroke Treatment", "benefit_3" => "Memory Care", "benefit_4" => "", "link_text" => "Learn More", "link_url" => "service-details.html", "emergency_button_text" => "", "emergency_button_icon" => "", "emergency_button_url" => "", "directions_button_text" => "", "directions_button_icon" => "", "directions_button_url" => ""]],
                ["item_index" => 6, "item_label" => "Orthopedics", "default_visible" => 1, "defaults" => ["category_key" => "specialty", "column_class" => "col-lg-6", "variant_class" => "", "icon_class" => "fa fa-bone", "title" => "Orthopedics", "description" => "Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit.", "benefit_1" => "Joint Replacement", "benefit_2" => "Sports Medicine", "benefit_3" => "Pain Management", "benefit_4" => "", "link_text" => "Learn More", "link_url" => "service-details.html", "emergency_button_text" => "", "emergency_button_icon" => "", "emergency_button_url" => "", "directions_button_text" => "", "directions_button_icon" => "", "directions_button_url" => ""]],
                ["item_index" => 7, "item_label" => "Oncology", "default_visible" => 1, "defaults" => ["category_key" => "specialty", "column_class" => "col-lg-6", "variant_class" => "", "icon_class" => "fa fa-user-nurse", "title" => "Oncology", "description" => "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis.", "benefit_1" => "Cancer Treatment", "benefit_2" => "Chemotherapy", "benefit_3" => "Support Services", "benefit_4" => "", "link_text" => "Learn More", "link_url" => "service-details.html", "emergency_button_text" => "", "emergency_button_icon" => "", "emergency_button_url" => "", "directions_button_text" => "", "directions_button_icon" => "", "directions_button_url" => ""]],
                ["item_index" => 8, "item_label" => "Laboratory Testing", "default_visible" => 1, "defaults" => ["category_key" => "diagnostics", "column_class" => "col-lg-6", "variant_class" => "", "icon_class" => "fa fa-vial", "title" => "Laboratory Testing", "description" => "Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam.", "benefit_1" => "Blood Analysis", "benefit_2" => "Pathology Services", "benefit_3" => "Quick Results", "benefit_4" => "", "link_text" => "Learn More", "link_url" => "service-details.html", "emergency_button_text" => "", "emergency_button_icon" => "", "emergency_button_url" => "", "directions_button_text" => "", "directions_button_icon" => "", "directions_button_url" => ""]],
                ["item_index" => 9, "item_label" => "Diagnostic Imaging", "default_visible" => 1, "defaults" => ["category_key" => "diagnostics", "column_class" => "col-lg-6", "variant_class" => "", "icon_class" => "fa fa-x-ray", "title" => "Diagnostic Imaging", "description" => "Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.", "benefit_1" => "MRI Scans", "benefit_2" => "CT Imaging", "benefit_3" => "Ultrasound", "benefit_4" => "", "link_text" => "Learn More", "link_url" => "service-details.html", "emergency_button_text" => "", "emergency_button_icon" => "", "emergency_button_url" => "", "directions_button_text" => "", "directions_button_icon" => "", "directions_button_url" => ""]],
                ["item_index" => 10, "item_label" => "24/7 Emergency Care", "default_visible" => 1, "defaults" => ["category_key" => "emergency", "column_class" => "col-lg-12", "variant_class" => "emergency-highlight", "icon_class" => "fa fa-ambulance", "title" => "24/7 Emergency Care", "description" => "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.", "benefit_1" => "Round-the-Clock Availability", "benefit_2" => "Trauma Center", "benefit_3" => "Critical Care Unit", "benefit_4" => "Emergency Surgery", "link_text" => "", "link_url" => "", "emergency_button_text" => "Call Emergency", "emergency_button_icon" => "fa fa-phone", "emergency_button_url" => "tel:911", "directions_button_text" => "Get Directions", "directions_button_icon" => "fa fa-map-marker-alt", "directions_button_url" => "directions.html"]],
            ],
        ],
    ],
];
