<?php

return [
    "template_key" => "terms",
    "template_name" => "Términos de servicio",
    "simple_fields" => [
        ["field_key" => "hero_title", "label" => "Titulo principal", "field_type" => "text", "default" => "Terms", "default_visible" => 1],
        ["field_key" => "hero_subtitle", "label" => "Subtitulo principal", "field_type" => "textarea", "default" => "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut elit tellus, luctus nec ullamcorper mattis, pulvinar dapibus leo.", "default_visible" => 1],
        ["field_key" => "last_updated", "label" => "Ultima actualizacion", "field_type" => "text", "default" => "Last Updated: February 27, 2025", "default_visible" => 1],
        ["field_key" => "terms_title", "label" => "Titulo terminos", "field_type" => "text", "default" => "Terms of Service", "default_visible" => 1],
        ["field_key" => "terms_intro", "label" => "Intro terminos", "field_type" => "text", "default" => "Please read these terms of service carefully before using our services", "default_visible" => 1],
        ["field_key" => "agreement_title", "label" => "Agreement titulo", "field_type" => "text", "default" => "1. Agreement to Terms", "default_visible" => 1],
        ["field_key" => "agreement_text", "label" => "Agreement texto", "field_type" => "textarea", "default" => "By accessing our website and services, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any of these terms, you are prohibited from using or accessing our services.", "default_visible" => 1],
        ["field_key" => "agreement_info_icon", "label" => "Info icono", "field_type" => "text", "default" => "bi bi-info-circle", "default_visible" => 1],
        ["field_key" => "agreement_info_text", "label" => "Info texto", "field_type" => "textarea", "default" => "These terms apply to all users, visitors, and others who access or use our services.", "default_visible" => 1],
        ["field_key" => "ip_title", "label" => "Intellectual property titulo", "field_type" => "text", "default" => "2. Intellectual Property Rights", "default_visible" => 1],
        ["field_key" => "ip_text", "label" => "Intellectual property texto", "field_type" => "textarea", "default" => "Our service and its original content, features, and functionality are owned by us and are protected by international copyright, trademark, patent, trade secret, and other intellectual property laws.", "default_visible" => 1],
        ["field_key" => "accounts_title", "label" => "Accounts titulo", "field_type" => "text", "default" => "3. User Accounts", "default_visible" => 1],
        ["field_key" => "accounts_text", "label" => "Accounts texto", "field_type" => "textarea", "default" => "When you create an account with us, you must provide accurate, complete, and current information. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account.", "default_visible" => 1],
        ["field_key" => "alert_icon", "label" => "Alert icono", "field_type" => "text", "default" => "bi bi-exclamation-triangle", "default_visible" => 1],
        ["field_key" => "alert_title", "label" => "Alert titulo", "field_type" => "text", "default" => "Important Notice", "default_visible" => 1],
        ["field_key" => "alert_text", "label" => "Alert texto", "field_type" => "textarea", "default" => "You are responsible for safeguarding the password and for all activities that occur under your account.", "default_visible" => 1],
        ["field_key" => "prohibited_title", "label" => "Prohibited titulo", "field_type" => "text", "default" => "4. Prohibited Activities", "default_visible" => 1],
        ["field_key" => "prohibited_text", "label" => "Prohibited texto", "field_type" => "textarea", "default" => "You may not access or use the Service for any purpose other than that for which we make it available.", "default_visible" => 1],
        ["field_key" => "disclaimer_title", "label" => "Disclaimers titulo", "field_type" => "text", "default" => "5. Disclaimers", "default_visible" => 1],
        ["field_key" => "disclaimer_text", "label" => "Disclaimers texto", "field_type" => "textarea", "default" => "Your use of our service is at your sole risk. The service is provided \"AS IS\" and \"AS AVAILABLE\" without warranties of any kind, whether express or implied.", "default_visible" => 1],
        ["field_key" => "disclaimer_intro", "label" => "Disclaimer box intro", "field_type" => "text", "default" => "We do not guarantee that:", "default_visible" => 1],
        ["field_key" => "limitation_title", "label" => "Limitation titulo", "field_type" => "text", "default" => "6. Limitation of Liability", "default_visible" => 1],
        ["field_key" => "limitation_text", "label" => "Limitation texto", "field_type" => "textarea", "default" => "In no event shall we be liable for any indirect, punitive, incidental, special, consequential, or exemplary damages arising out of or in connection with your use of the service.", "default_visible" => 1],
        ["field_key" => "indemnification_title", "label" => "Indemnification titulo", "field_type" => "text", "default" => "7. Indemnification", "default_visible" => 1],
        ["field_key" => "indemnification_text", "label" => "Indemnification texto", "field_type" => "textarea", "default" => "You agree to defend, indemnify, and hold us harmless from and against any claims, liabilities, damages, losses, and expenses arising out of your use of the service.", "default_visible" => 1],
        ["field_key" => "termination_title", "label" => "Termination titulo", "field_type" => "text", "default" => "8. Termination", "default_visible" => 1],
        ["field_key" => "termination_text", "label" => "Termination texto", "field_type" => "textarea", "default" => "We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.", "default_visible" => 1],
        ["field_key" => "law_title", "label" => "Governing law titulo", "field_type" => "text", "default" => "9. Governing Law", "default_visible" => 1],
        ["field_key" => "law_text", "label" => "Governing law texto", "field_type" => "textarea", "default" => "These Terms shall be governed by and construed in accordance with the laws of [Your Country], without regard to its conflict of law provisions.", "default_visible" => 1],
        ["field_key" => "changes_title", "label" => "Changes titulo", "field_type" => "text", "default" => "10. Changes to Terms", "default_visible" => 1],
        ["field_key" => "changes_text", "label" => "Changes texto", "field_type" => "textarea", "default" => "We reserve the right to modify or replace these Terms at any time. We will provide notice of any changes by posting the new Terms on this page.", "default_visible" => 1],
        ["field_key" => "notice_icon", "label" => "Notice icono", "field_type" => "text", "default" => "bi bi-bell", "default_visible" => 1],
        ["field_key" => "notice_text", "label" => "Notice texto", "field_type" => "textarea", "default" => "By continuing to access or use our service after those revisions become effective, you agree to be bound by the revised terms.", "default_visible" => 1],
        ["field_key" => "contact_icon", "label" => "Contacto icono", "field_type" => "text", "default" => "bi bi-envelope", "default_visible" => 1],
        ["field_key" => "contact_title", "label" => "Contacto titulo", "field_type" => "text", "default" => "Questions About Terms?", "default_visible" => 1],
        ["field_key" => "contact_text", "label" => "Contacto texto", "field_type" => "textarea", "default" => "If you have any questions about these Terms, please contact us.", "default_visible" => 1],
        ["field_key" => "contact_link_text", "label" => "Contacto enlace texto", "field_type" => "text", "default" => "Contact Support", "default_visible" => 1],
        ["field_key" => "contact_link_url", "label" => "Contacto enlace URL", "field_type" => "url", "default" => "#", "default_visible" => 1],
    ],
    "repeaters" => [
        [
            "repeater_key" => "ip_items",
            "label" => "Intellectual property items",
            "fields" => [
                ["field_key" => "text", "label" => "Texto", "field_type" => "text", "default" => ""],
            ],
            "items" => [
                ["item_index" => 0, "item_label" => "All content is our exclusive property", "default_visible" => 1, "defaults" => ["text" => "All content is our exclusive property"]],
                ["item_index" => 1, "item_label" => "You may not copy or modify the content", "default_visible" => 1, "defaults" => ["text" => "You may not copy or modify the content"]],
                ["item_index" => 2, "item_label" => "Our trademarks may not be used without permission", "default_visible" => 1, "defaults" => ["text" => "Our trademarks may not be used without permission"]],
                ["item_index" => 3, "item_label" => "Content is for personal, non-commercial use only", "default_visible" => 1, "defaults" => ["text" => "Content is for personal, non-commercial use only"]],
            ],
        ],
        [
            "repeater_key" => "prohibited_items",
            "label" => "Prohibited items",
            "fields" => [
                ["field_key" => "icon_class", "label" => "Icono", "field_type" => "text", "default" => "bi bi-x-circle"],
                ["field_key" => "text", "label" => "Texto", "field_type" => "text", "default" => ""],
            ],
            "items" => [
                ["item_index" => 0, "item_label" => "Systematic retrieval of data or content", "default_visible" => 1, "defaults" => ["icon_class" => "bi bi-x-circle", "text" => "Systematic retrieval of data or content"]],
                ["item_index" => 1, "item_label" => "Publishing malicious content", "default_visible" => 1, "defaults" => ["icon_class" => "bi bi-x-circle", "text" => "Publishing malicious content"]],
                ["item_index" => 2, "item_label" => "Engaging in unauthorized framing", "default_visible" => 1, "defaults" => ["icon_class" => "bi bi-x-circle", "text" => "Engaging in unauthorized framing"]],
                ["item_index" => 3, "item_label" => "Attempting to gain unauthorized access", "default_visible" => 1, "defaults" => ["icon_class" => "bi bi-x-circle", "text" => "Attempting to gain unauthorized access"]],
            ],
        ],
        [
            "repeater_key" => "disclaimer_items",
            "label" => "Disclaimer items",
            "fields" => [
                ["field_key" => "text", "label" => "Texto", "field_type" => "text", "default" => ""],
            ],
            "items" => [
                ["item_index" => 0, "item_label" => "The service will meet your requirements", "default_visible" => 1, "defaults" => ["text" => "The service will meet your requirements"]],
                ["item_index" => 1, "item_label" => "The service will be uninterrupted or error-free", "default_visible" => 1, "defaults" => ["text" => "The service will be uninterrupted or error-free"]],
                ["item_index" => 2, "item_label" => "Results from using the service will be accurate", "default_visible" => 1, "defaults" => ["text" => "Results from using the service will be accurate"]],
                ["item_index" => 3, "item_label" => "Any errors will be corrected", "default_visible" => 1, "defaults" => ["text" => "Any errors will be corrected"]],
            ],
        ],
    ],
];
